name: salarying CI/CD


on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main ]


env:
  S3_BUCKET_NAME: final-salarying-s3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

      # application.properties 파일 생성
    - name: Make application-redis.properties
      run: |
        cd ./src/main/resources
        touch ./application-redis.properties

        echo "${{ secrets.REDIS_PROPERTIES }}" >> ./application-redis.properties
      shell: bash

    - name: Make application-profile.properties
      run: |
        cd ./src/main/resources
        touch ./application-profile.properties
        
        echo "${{ secrets.DATABASE_PROPERTIES }}" >> ./application-profile.properties
      shell: bash

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'kdt3final'
        mysql user: 'admin'
        mysql password: ${{ secrets.DATABASE_PASSWORD }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build


#디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    - name: Copy appspec.yml to deploy
      run: cp appspec.yml ./deploy

    - name: Copy deploy.sh to deploy
      run: cp deploy.sh ./deploy

# Jar파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    - name: Make zip file
      run: zip -r ./Final-Project-3-BE.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./Final-Project-3-BE.zip s3://$S3_BUCKET_NAME/

# Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run:
        aws deploy create-deployment
        --application-name salarying-codedeploy
        --deployment-group-name salarying-group
        --file-exists-behavior OVERWRITE
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=Final-Project-3-BE.zip
        --region ap-northeast-2
